/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package responsi;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.Scanner;
import java.awt.*;
/**
 *
 * @author lenovo
 */
public class FormUpdate extends javax.swing.JFrame {
    ResultSet RsProduk=null;
    /** Creates new form FormUpdate */
    public FormUpdate() {
        initComponents();
        
        Dimension screenSize=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize=this.getSize();
        if(frameSize.height > screenSize.height){
        frameSize.height=screenSize.height;
        }
        if(frameSize.width > screenSize.width){
        frameSize.width=screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) / 2,
        (screenSize.height = screenSize.height) / 20); 
        
        BersihData();
        inputIDUD.setEnabled(true);
        inputJudulUD.setEnabled(false);
        inputGenreUD.setEnabled(false);
        inputPenulisUD.setEnabled(false);
        inputPenerbitUD.setEnabled(false);       
        inputLokasiUD.setEnabled(false);
        inputStokUD.setEnabled(false);
    }
    
    //menampilkan data ke form saat data pada tabel di klik 
   void tblKeForm(){
        try{
            String id=inputIDUD.getText();
            Connection conn=(Connection)koneksi.koneksiDB();
            Statement stt=conn.createStatement();
            
            RsProduk=stt.executeQuery("SELECT * FROM buku WHERE id='"+id+"'");  
            while(RsProduk.next()){
                    inputIDUD.setText(RsProduk.getString("id"));
                    inputJudulUD.setText(RsProduk.getString("judul"));
                    inputGenreUD.setSelectedItem(RsProduk.getString("genre"));
                    inputPenulisUD.setText(RsProduk.getString("penulis"));
                    inputPenerbitUD.setText(RsProduk.getString("penerbit"));        
                    inputLokasiUD.setSelectedItem(RsProduk.getString("lokasi"));
                    inputStokUD.setText(RsProduk.getString("stok"));
             
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }  
    }
    //membersihkan form
   private void BersihData(){
        inputIDUD.setText("");
        inputJudulUD.setText("");
        inputGenreUD.setSelectedIndex(0);
        inputPenulisUD.setText("");
        inputPenerbitUD.setText("");        
        inputLokasiUD.setSelectedIndex(0);
        inputStokUD.setText("");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputIDUD = new javax.swing.JTextField();
        inputJudulUD = new javax.swing.JTextField();
        inputGenreUD = new javax.swing.JComboBox<>();
        inputPenulisUD = new javax.swing.JTextField();
        inputPenerbitUD = new javax.swing.JTextField();
        inputLokasiUD = new javax.swing.JComboBox<>();
        inputStokUD = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        okUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("FORM UPDATE DATA BUKU");

        jLabel2.setText("ID Buku");

        jLabel3.setText("Judul Buku");

        jLabel4.setText("Genre");

        jLabel5.setText("Penulis");

        jLabel6.setText("Penerbit");

        jLabel7.setText("Lokasi");

        jLabel8.setText("Stok");

        inputGenreUD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motivation", "Action", "Tragedy", "Comedy", "Romance", "Horror", "Mystery", "Adventure" }));

        inputLokasiUD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LT 1A", "LT 1B", "LT 1C", "LT 2A", "LT 2B", "LT 2C" }));

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        okUpdate.setText("OK");
        okUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okUpdateActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(86, 86, 86)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(layout.createSequentialGroup()
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(jLabel3)
                                                .add(jLabel4)
                                                .add(jLabel5))
                                            .add(23, 23, 23))
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                            .add(jLabel6)
                                            .add(34, 34, 34)))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel7)
                                            .add(jLabel8)
                                            .add(jLabel2))
                                        .add(45, 45, 45)))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, inputLokasiUD, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, inputPenerbitUD)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, inputPenulisUD)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, inputGenreUD, 0, 161, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, inputJudulUD)
                                    .add(inputStokUD)))
                            .add(update, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(okUpdate))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(inputIDUD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel1))
                        .add(0, 80, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(inputIDUD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(okUpdate))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(inputJudulUD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(inputGenreUD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(inputPenulisUD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(inputPenerbitUD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(inputLokasiUD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(inputStokUD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(update)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String id=inputIDUD.getText();
        String judul=inputJudulUD.getText();
        String genre=inputGenreUD.getSelectedItem().toString();
        String penulis=inputPenulisUD.getText();
        String penerbit=inputPenerbitUD.getText();
        String lokasi=inputLokasiUD.getSelectedItem().toString();
        String stok=inputStokUD.getText();


        if (id.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"ID Buku tidak boleh kosong");
            inputIDUD.requestFocus();
        }else if (judul.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Judul buku tidak boleh kosong");
            inputJudulUD.requestFocus();
        }else if (genre.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Genre tidak boleh kosong");
            inputGenreUD.requestFocus();
        }else if (penulis.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Penulis tidak boleh kosong");
            inputPenulisUD.requestFocus();
        }
        else if (penerbit.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Penerbit tidak boleh kosong");
            inputPenerbitUD.requestFocus();
        }
        else if (lokasi.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Lokasi tidak boleh kosong");
            inputLokasiUD.requestFocus();
        }
        else if (stok.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Stok tidak boleh kosong");
            inputStokUD.requestFocus();
        }
        else{
            try{
                Connection conn=(Connection)koneksi.koneksiDB();
                Statement stt=conn.createStatement();
                stt.executeUpdate("UPDATE buku SET judul='"+judul+"', genre='"+genre+"', penulis='"+penulis+"',"+
                    "penerbit='"+penerbit+"', lokasi='"+lokasi+"', stok='"+stok+"' WHERE id='"+id+"'");
                BersihData();
                JOptionPane.showMessageDialog(this,"Data berhasil diupdate, silakan klik 'Tampilkan Semua' untuk melihat data terkini !","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Simpan data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        //exit
        dispose();
    }//GEN-LAST:event_updateActionPerformed

    private void okUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okUpdateActionPerformed
        // TODO add your handling code here:
        inputIDUD.setEnabled(false);
        inputJudulUD.setEnabled(true);
        inputGenreUD.setEnabled(true);
        inputPenulisUD.setEnabled(true);
        inputPenerbitUD.setEnabled(true);       
        inputLokasiUD.setEnabled(true);
        inputStokUD.setEnabled(true);
        tblKeForm();
    }//GEN-LAST:event_okUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUpdate().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> inputGenreUD;
    private javax.swing.JTextField inputIDUD;
    private javax.swing.JTextField inputJudulUD;
    private javax.swing.JComboBox<String> inputLokasiUD;
    private javax.swing.JTextField inputPenerbitUD;
    private javax.swing.JTextField inputPenulisUD;
    private javax.swing.JTextField inputStokUD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton okUpdate;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

}
